export const BitcoinStatsType = {
    GET_BITCOIN_STATS_PENDING: 'GET_BITCOIN_STATS_PENDING',
    GET_BITCOIN_STATS_SUCCESS: 'GET_BITCOIN_STATS_SUCCESS',
    GET_BITCOIN_STATS_FAILED: 'GET_BITCOIN_STATS_FAILED'
};
